### PR TITLE
Add GitHub Actions CI

### LINKED ISSUE #2: fix CI rendering
The current CI is *trying* to render the "example.toml" skill tree whenever master changes, so that we can give people an up-to-date look at how things look when rendered, but it encounters some weird errors. This is a result of me pulling my hair out trying to read the deploy-key docs on travis, mostly. Somebody help!

### PR DESCRIPTION
**Pull request by XAMPPRocky**
fixes #2 

This changes the CI to use GitHub Actions instead of Travis, adding testing, as well as creating and publishing the example output to GitHub Pages. I haven't actually removed the travis CI, as it seems there are some other files like `deploy-key-skill-tree.enc` that I don't know if you want to keep. I can also remove in this PR if it's decided they're no longer needed.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Gah! I missed this PR for ages and ages, sorry @XAMPPRocky

**Comment by nikomatsakis** [comment]
Apparently I was not watching this repo :)

**Comment by nikomatsakis** [comment]
I am happy to remove the travis infra and random `.enc` files related to it

**Comment by nikomatsakis** [comment]
That said, I can't quite tell what this workflow does -- do I need to setup a `GITHUB_TOKEN` or something to publish?

**Comment by XAMPPRocky** [comment]
> That said, I can't quite tell what this workflow does -- do I need to setup a GITHUB_TOKEN or something to publish?

Nope, `GITHUB_TOKEN` is something every repository has access to in [GitHub Actions](https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token). Previously there was a bug were it couldn't be used for GitHub Pages deployment, so you had to setup a seperate token, but that's been fixed now so there's no setup required. 🙂 

The `create_example_output.yml` will run the example code on any master push and publish changes using [github-pages-deploy-action][gha]. This is the same action we've been using on the [blog](https://github.com/rust-lang/blog.rust-lang.org/blob/master/.github/workflows/main.yml#L23) and on forge, and it has worked really well so far.

[gha]: https://github.com/JamesIves/github-pages-deploy-action

**Comment by nikomatsakis** [comment]
@XAMPPRocky this seems awesome! Can you remove the travis config -- do I have to do something to enable github actions?

**Comment by XAMPPRocky** [comment]
@nikomatsakis Removed the config

> do I have to do something to enable github actions?

Once this PR is merged it should be automatically enabled.

**Comment by nikomatsakis** [comment]
Let's find out! Thanks @XAMPPRocky

**Comment by XAMPPRocky** [comment]
@nikomatsakis Looks good to me :) The one thing that does need to be explicitly enabled that I only just remembered is GitHub Pages.

**Pull request merged**
